# Generated by Django 4.2.1 on 2023-05-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="copies",
            field=models.ManyToManyField(
                related_name="users", through="copies.Book_loans", to="copies.copies"
            ),
        ),
    ]
