# Generated by Django 4.2.1 on 2023-05-04 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_copies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_stundent",
            new_name="is_student",
        ),
    ]
