# Generated by Django 4.2.1 on 2023-05-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0004_alter_copies_book"),
        ("users", "0003_rename_is_stundent_user_is_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="copies",
        ),
        migrations.AddField(
            model_name="user",
            name="loans",
            field=models.ManyToManyField(
                related_name="users", through="copies.Book_loans", to="copies.copies"
            ),
        ),
    ]
