# Generated by Django 4.2.1 on 2023-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_blocked_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blocked_until",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
