# Generated by Django 4.2.1 on 2023-05-03 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="followings",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="followings",
            old_name="user_id",
            new_name="user",
        ),
    ]
