# Generated by Django 4.2.1 on 2023-05-03 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_rename_copie_id_book_loans_copie_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copies",
            old_name="book_id",
            new_name="book",
        ),
    ]
