# Generated by Django 4.2.1 on 2023-05-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_author"),
        ("copies", "0003_rename_book_id_copies_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copies",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.book",
            ),
        ),
    ]
