# Generated by Django 4.2.1 on 2023-05-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0004_alter_copies_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_loans",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book_loans",
            name="status",
            field=models.CharField(
                choices=[("Not Returned", "Not Returned"), ("Returned", "Returned")],
                default="Not Returned",
                max_length=15,
            ),
        ),
    ]
