# Generated by Django 4.2.1 on 2023-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0006_remove_copies_is_avaible_copies_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copies",
            name="is_available",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
