# Generated by Django 4.2.1 on 2023-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0008_alter_book_loans_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_loans",
            name="status",
            field=models.CharField(
                choices=[
                    ("Borrowed", "Borrowed"),
                    ("Returned", "Returned"),
                    ("Delayed", "Delayed"),
                ],
                default="Borrowed",
                max_length=10,
            ),
        ),
    ]
