# Generated by Django 4.2.1 on 2023-05-05 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_copies_user_loans"),
        ("books", "0004_alter_book_year"),
        ("copies", "0010_rename_copie_book_loans_copies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Copies",
            new_name="Copy",
        ),
        migrations.RenameField(
            model_name="book_loans",
            old_name="copies",
            new_name="copy",
        ),
    ]
